authors = ["Brian Doolittle <brian.d.doolittle@gmail.com> and contributors"]
version = "0.0.1"

[deps]
BellScenario = "4e58fcc1-4405-48af-b0f2-42df636d9190"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
QBase = "e52e8ede-12bf-4731-8af7-b01f6064cb11"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BellScenario = "0.1.3"
Combinatorics = "1"
QBase = "0.2"
julia = "1"
